# Sui
SUI_PRIVATE_KEY=your_hex_private_key_here
SUI_NETWORK=testnet

# Package IDs (from sui client publish output)
PACKAGE_ID=0x...
AGENT_REGISTRY_ID=0x...
TASK_BOARD_ID=0x...

# Agent IDs (from registration)
AGENT_CARD_ID=0x...
DELEGATION_CAP_ID=0x...
REPUTATION_RECORD_ID=0x...

# Walrus (optional)
WALRUS_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space
